# Site
name: "Fadal Store"
title: "Fadal Store"
description: "Maqaallo, Tababaro iyo Agabka Ganacsiga Online-ka."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
url: "https://fadalstore.github.io" # Halkan ayaan ka saxnay .com
google_analytics: ''
disqus: ''
mailchimp-list: 'https://formspree.io/f/fadalstore@gmail.com'
include: ["_pages"]
permalink: /:title.html

# Authors
authors:
  fadal:
    name: Fadal
    display_name: Fadal
    avatar: 'assets/images/avatar.jpg'
    email: fadalstore7@gmail.com # Kan waad iska deyn kartaa haddii uu shaqaynayo
    web: https://fadalstore.github.io
    twitter: https://x.com/fadalsheekh?s=21
    telegram: https://t.me/fadalsheekh
    facebook: https://www.facebook.com/share/1Cd2CGo1W1/?mibextid=wwXIfr
    whatsapp: https://wa.me/message/B4E27ZTETP3CG1
    youtube: https://youtube.com/@hiig-c4c?si=ijjeBnnEA9HhV_N3
    description: "Fadal waa khabiir ku takhasusay ganacsiga online-ka iyo horumarinta website-yada."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense
adsense: "enabled"
adsense_data_ad_client: "ca-pub-9732596199385216"
adsense_data_ad_slot: "auto"

# Lazy Images
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, backup_fadal, attached_assets, check_links.py, check_orphans.py, fix_and_generate.js, generate_articles.js, generate_english.js, generate_programming.js, generate_sitemap.py, package-lock.json, package.json, serve.json, .local, .replit, replit.nix]
