# Site
name: "Fadal Store"
title: "Fadal Store"
description: "Maqaallo, Tababaro iyo Agabka Ganacsiga Online-ka."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
url: "https://fadalstore.com"
google_analytics: ''
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title.html

# Authors
authors:
  fadal:
    name: Fadal
    display_name: Fadal
    avatar: 'assets/images/avatar.png'
    email: contact@fadalstore.com
    web: https://fadalstore.github.io
    twitter: https://twitter.com/fadalstore
    description: "Fadal waa khabiir ku takhasusay ganacsiga online-ka iyo horumarinta website-yada."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense
adsense: "enabled"
adsense-data-ad-client: "ca-pub-9732596199385216"
adsense-data-ad-slot: "auto"

# Lazy Images
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, backup_fadal, attached_assets, check_links.py, check_orphans.py, fix_and_generate.js, generate_articles.js, generate_english.js, generate_programming.js, generate_sitemap.py, package-lock.json, package.json, serve.json, .local, .replit, replit.nix]
